# Generated by Django 5.2.7 on 2025-10-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(blank=True, default='', upload_to='pokemons'),
            preserve_default=False,
        ),
    ]
