# Generated by Django 2.2.24 on 2025-10-08 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_auto_20251008_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='photo',
            field=models.ImageField(upload_to='pokemons', verbose_name='картинка'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 19, 29, 36, 558711, tzinfo=utc), verbose_name='время появления на карте'),
        ),
        migrations.AlterField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 8, 19, 29, 36, 558711, tzinfo=utc), verbose_name='время исчезновения на карте'),
        ),
    ]
